# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 76ba885e9ff266b3c04cd6d3cf1f51eb5abccefbfdb2f77c359d889a1a55f5318b0929495a6e13d2b9cf28ff5dc1a9b09433398e60c55a3d7e5710e72371823e

test:
  secret_key_base: 50901f28ca12d6f2d0583baaf8caf5b405a6a26b3b8f11d26ba5c6132850bbd68d6682501d2eeb0061b7d9c10b62433662f43554fec7893582fd4403dfd3aee6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
